version: 2.1

orbs:
  architect: giantswarm/architect@0.10.2

workflows:
  go-build:
    jobs:
      - architect/push-to-docker:
          name: push-run-sonobuoy-tests-to-quay
          context: architect
          image: "quay.io/giantswarm/run-sonobuoy-tests"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/
